Refactoring of Compiler.cs and adding first version of the new SPython language parser
pascalabcnet/pascalabcnet pull request #2984
Opened 2023-12-10 16:08 UTC by AlexanderZemlyak

Произведен рефакторинг файла Compiler.cs с целью улучшения читаемости кода. Также добавлена первая версия парсера для нового языка - SPython (статический питон).

2023-12-10 16:48 UTC, samuraiGH commented
>Также добавлена первая версия парсера для нового языка - SPython (статический питон)
А почему это не вынесено в форк допустим? Не совсем понимаю, зачем в одном компиляторе несколько языков поддерживать

Если Вы хотите сделать язык с синтаксисом питона и самантикой pabc, используя одно и то же семантическое дерево и его обработчики, то может быть стоит эту общую часть распространять как nuget-пакет(ы)? Тогда то, что сделано в этом PR можно будет спокойно пилить в отдельном репозитории

Лично я против мержа этого в основной репозиторий. Кодовая база для понимая тут и так сложна, не стоит её ещё больше усложнять

2023-12-10 19:55 UTC, AlexanderZemlyak commented
> > Также добавлена первая версия парсера для нового языка - SPython (статический питон)
> 
> А почему это не вынесено в форк допустим? Не совсем понимаю, зачем в одном компиляторе несколько языков поддерживать
> 
> Если Вы хотите сделать язык с синтаксисом питона и семантикой pabc, используя одно и то же семантическое дерево и его обработчики, то может быть стоит эту общую часть распространять как nuget-пакет(ы)? Тогда то, что сделано в этом PR можно будет спокойно пилить в отдельном репозитории
> 
> Лично я против мержа этого в основной репозиторий. Кодовая база для понимая тут и так сложна, не стоит её ещё больше усложнять

Ваши замечания учтены. Изменения, связанные с новым языком пока что решено отменить.

2023-12-10 19:55 UTC, SunSerega requested changes
В целом годно, только к мелочам придраться могу.

Вокруг `public string Compile()` всё сильно перетасовалось, так что более подробно по тому коду не посоветую. Но этот как раз полевыми испытаниями должно хорошо покрыться.

Что касается моего ревью:
Каждый изначальный комментарий создаёт свой тред. Их удобно рассматривать по одному.
Когда говорить в треде больше не о чем - нажимаете `resolved` под этим тредом. После этого можно продолжать комментировать, но при загрузке страницы его теперь будет изначально показывать свёрнутым, чтобы не мешался.

Самый первый комментарий ещё содержит предложение изменений - у вас должна быть кнопка чтобы сразу его влить. Если нажмёте - создастся комит, у которого я и вы будем ко-авторами.

2023-12-10 19:55 UTC, SunSerega commented on .gitignore
> +**/UniversalParserHelper.dll
```suggestion
**/UniversalParserHelper.dll

```
Перенос строки потратили, вместо добавления новой строки.

2023-12-10 19:55 UTC, SunSerega commented on Compiler/Compiler.cs
> +using System.Reflection;
Сортировка по алфавиту? Ну, то что было раньше не сильно лучше, но если уже менять файл в целях читабельности - уже б по какой-то логике `using` раставили бы...

2023-12-10 19:55 UTC, SunSerega commented on Compiler/Compiler.cs
> +        public SyntaxTree.compilation_unit SyntaxTree
Из 1639 табов в этом файле - 339 ещё остались. Может добьёте их? В студии для этого вроде специальная кнопка есть.

2023-12-10 19:55 UTC, SunSerega commented on ParserTools/ParsersController.cs
> +                //if (Path.GetFileName(fi.FullName) == "VeryBasicLanguageParser.dll")
Я так понимаю это со времени дебага осталось. Но теперь оно незачем.

Чтобы ловить и не коммитить такое - стоит перед коммитом всегда хотя бы бегло пролистывать изменённые файлы.

2023-12-10 19:55 UTC, SunSerega commented on ParserTools/ParsersController.cs
> +                /*catch (System.Reflection.ReflectionTypeLoadException e)
Ну и тут так же. Хотя его можно было бы оставить (закомментированным), если б оно информацию на консоль выводило, а не только переменные создавало.

И рекомендую для временно закомментированных блоков использовать такой патерн:
```
/**
code
/**/
```
Это можно быстро раскомментировать и закомментированных  назад, одним слешем.
А если использовать то что даёт IDE по сочетанию клавиш - надо каждый раз правильно выделять чтобы мимо не пошло.

2023-12-10 19:55 UTC, SunSerega commented on Studio.bat
> +) else if exist "D:\apps for coding\VisualStudio\MSBuild\Current\Bin\MSBuild.exe" (
Мда, это не красиво конечно, но я не уверен как лучше. Может в переменную `Path` его добавить и тут эту переменную тестировать, вместо супер-конкретного пути?

2023-12-10 19:55 UTC, SunSerega commented on TreeConverter/TreeConversion/CompilationErrors.cs
> +            : base("???", "Undefined file_name")
Случайно изменили?

2023-12-10 19:55 UTC, SunSerega commented on Compiler/Compiler.cs
> +        private bool IsPossibleNetNamespaceOrStandardPasFile(SyntaxTree.unit_or_namespace name_space, bool addToStandardModules, string currentPath)
На сколько я помню, проверка на стандартный файл была побочной...
Ну, кроме названия - надо всё же доразобраться, мне кажется объяснение от @ibond84 всё же не полное. Повторюсь тут: чтобы не добавлять модули в RTL - их надо убрать из `uses` исходного .pas файла для RTL.

2023-12-10 19:55 UTC, SunSerega commented on ReleaseGenerators/sect_Core.nsh
> +	File "..\bin\ShiftReduceParser.dll"
Таб вместо пробелов. И так же в нескольких местах ниже в этом же файле.

2023-12-10 19:55 UTC, SunSerega commented on ShiftReduceParser/ShiftReduceParserCode.cs
А это, я так понимаю, вы вынесли в отдельный проект без изменений, правильно?

2023-12-10 19:55 UTC, SunSerega commented on SyntaxTree/tree/TreeSubsidiary.cs
> +        /// ��������� ����������� (����������� ���� �������� �������, ��� ������������� ������� ������ �����)
Кодировка сломана. Конвертируйте UTF8+BOM наверное?

2023-12-10 19:55 UTC, SunSerega commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
Можете прокомментировать эту часть? Что оно делало и зачем делать чтобы только для релиза компилировалось?

2023-12-10 19:55 UTC, SunSerega commented on _Presentations/2015 New Features/Programs/06_ShortFunc.exe
Случайно добавили?

2023-12-10 19:55 UTC, SunSerega commented on bin/Highlighting/SPython.xshd
Тоже часть `SPython`

2023-12-10 19:55 UTC, SunSerega commented on bin/TestRunner.exe
Что тут поменялось? .pas файл ведь тот же. Может там зависимость от RTL случайно добавили, откомпилировав с включённым ускорением?

2023-12-10 19:55 UTC, SunSerega commented on Localization/DefaultLang.resources
Случайно удалили?

2023-12-10 20:15 UTC, AlexanderZemlyak commented on Compiler/Compiler.cs
> +        public SyntaxTree.compilation_unit SyntaxTree
А подскажите, что за кнопка.

2023-12-10 20:18 UTC, AlexanderZemlyak commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
Насчет этого сложно что-то сказать. Надо посмотреть кто изменял это.

2023-12-10 20:21 UTC, AlexanderZemlyak commented on _Presentations/2015 New Features/Programs/06_ShortFunc.exe
Да, вообще не представляю, как так вышло)

2023-12-10 20:32 UTC, SunSerega commented on Compiler/Compiler.cs
> +        public SyntaxTree.compilation_unit SyntaxTree
![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/3d7032b2-c565-4176-a734-53610df85d77)

Сейчас показывает MIXED - смешанные отступы в виде табов и пробелов. Можно тыкнуть и выбрать что то одно.

2023-12-10 20:39 UTC, SunSerega commented on Compiler/Compiler.cs
> +        public SyntaxTree.compilation_unit SyntaxTree
Желательно запушить коммит который резолвит перед тем как нажимать резолв. Чтобы пока горячо - я мог посмотреть и если что ещё прокомментировать.

2023-12-10 20:42 UTC, SunSerega commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
Для этого как раз существует `git blame` - чтобы знать на ком blame (типа обвинение в изменениях)

В TortoiseGit есть фича с тем же именем, но на много более удобном UI (нормальный редактор с кучей кнопок вместо консоли)
В GitKraken, который больше похож на GitHub Desktop такого нет. В самом GitHub Desktop не знаю, но обычно в нём ещё меньше фич.

2023-12-10 20:43 UTC, SunSerega commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
А впрочем там только показывает что вы засквошили несколько коммитов, включая тот что это изменил.
![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/97d8fb8d-883b-4b5c-b4a1-34a644c5552d)
Но может хотя бы напомнит откуда это?

2023-12-10 20:45 UTC, SunSerega commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
С другой стороны - в описании этого коммита-сквоша есть hash-и всех комитов что в него зашли. Если повезёт - они ещё должны быть на гитхабе. Обычно их далеко не сразу удаляет, даже если удалили все ветки, ссылающиеся на эти комиты.

2023-12-10 20:49 UTC, AlexanderZemlyak commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
> Для этого как раз существует `git blame` - чтобы знать на ком blame (типа обвинение в изменениях)
> 
> В TortoiseGit есть фича с тем же именем, но на много более удобном UI (нормальный редактор с кучей кнопок вместо консоли) В GitKraken, который больше похож на GitHub Desktop такого нет. В самом GitHub Desktop не знаю, но обычно в нём ещё меньше фич.

Кстати, видел в GitKraken blame
![image](https://github.com/pascalabcnet/pascalabcnet/assets/92867056/e6766ebe-c597-40f2-b97e-dcfb96a1212f)

2023-12-10 20:58 UTC, SunSerega commented on VisualPascalABCNET/IB/CodeCompletion/CodeCompletionParserController.cs
> +#if DEBUG
О, и правда

2023-12-10 21:15 UTC, SunSerega commented
Кхм, решили всё в табы... Ну, хай будет, лишь бы одинаково.

2023-12-11 11:18 UTC, AlexanderZemlyak commented on ParserTools/ParsersController.cs
> +                //if (Path.GetFileName(fi.FullName) == "VeryBasicLanguageParser.dll")
Убрали

2023-12-11 11:20 UTC, AlexanderZemlyak commented on Localization/DefaultLang.resources
А он вроде есть

2023-12-11 11:48 UTC, SunSerega commented on Studio.bat
> +) else if exist "%MSBUILD_PATH%" (
Интересно, а откуда эта переменная? Её устанавливает студия, или вы сами себе забиваете?

2023-12-11 11:51 UTC, SunSerega commented on Localization/DefaultLang.resources
И правда, его только гитхаб почему то удалённым показывает в списке изменений...

2023-12-11 11:52 UTC, AlexanderZemlyak commented on Studio.bat
> +) else if exist "%MSBUILD_PATH%" (
Сам

2023-12-11 11:57 UTC, SunSerega commented on Studio.bat
> +) else if exist "%MSBUILD_PATH%" (
Я пока параллельно делал ещё 1 решение по другой причине - на моей ветке `MSBuild.exe` уже находит если он добавлен в `PATH`. Ну, ваше решение тоже можно оставить, если кому то ещё понадобится.

Только тогда отделите пустыми строками, как всё остальное. И желательно прокомметируйте, чтобы те кто после вас придут - знали для чего эта проверка.

2023-12-11 14:51 UTC, AlexanderZemlyak commented on Compiler/Compiler.cs
> +        private bool IsPossibleNetNamespaceOrStandardPasFile(SyntaxTree.unit_or_namespace name_space, bool addToStandardModules, string currentPath)
Ну она не совсем побочная, поскольку стандартные файлы, помимо их использования при построении "главного" семантического дерева, попадают в списки interfaceUsedUnits, implementationUsedUnits и possibleNamespaces, то есть воспринимаются как пространства имен, что очень странно.

2023-12-11 14:55 UTC, AlexanderZemlyak commented on ShiftReduceParser/ShiftReduceParserCode.cs
Да, все верно.

2023-12-11 15:29 UTC, AlexanderZemlyak commented on ReleaseGenerators/sect_Core.nsh
> +	File "..\bin\ShiftReduceParser.dll"
Ой, там во многих местах. При чем и до нас тоже были смешанные отступы. Вы думаете, стоит абсолютно везде пробелы поставить?

2023-12-11 15:45 UTC, SunSerega commented on SyntaxTree/tree/TreeSubsidiary.cs
> +	public enum proc_attribute {attr_override, attr_forward, attr_virtual, attr_overload, attr_reintroduce, attr_abstract, attr_static, attr_extension, attr_none }; // attr_none нужно для свойств когда
Символы всё ещё сломаны, и BOM в начале файла всё ещё нету.
Notepad++ позволяет прочитать файл в виде любой кодировки и затем пересохранить как другую.

2023-12-11 15:46 UTC, SunSerega commented on ReleaseGenerators/sect_Core.nsh
> +	File "..\bin\ShiftReduceParser.dll"
Кхм, и правда. Ну, я про пробелы думаю в первую очередь потому что их больше чем табов - чтобы меньше изменений показывало.

2023-12-11 18:00 UTC, AlexanderZemlyak commented on SyntaxTree/tree/TreeSubsidiary.cs
> +	public enum proc_attribute {attr_override, attr_forward, attr_virtual, attr_overload, attr_reintroduce, attr_abstract, attr_static, attr_extension, attr_none }; // attr_none нужно для свойств когда
Надеюсь, теперь все в порядке.

2023-12-11 18:48 UTC, AlexanderZemlyak commented on bin/TestRunner.exe
Да, похоже что Вы правы насчет зависимости. Тогда я верну старую версию этого файла.

2023-12-11 19:20 UTC, SunSerega commented on SyntaxTree/tree/TreeSubsidiary.cs
> +	public enum proc_attribute {attr_override, attr_forward, attr_virtual, attr_overload, attr_reintroduce, attr_abstract, attr_static, attr_extension, attr_none }; // attr_none нужно для свойств когда
Да, теперь всё исправилось.

2023-12-12 07:58 UTC, SunSerega commented on Compiler/Compiler.cs
> +        /// <summary>
Кхм, новые пробелы. Может стоит посмотреть в настройки студии? У меня при добавлении описания на пробелы не переключается...

2023-12-12 08:52 UTC, AlexanderZemlyak commented on Compiler/Compiler.cs
> +        /// <summary>
Это при копировании произошло. Включил опцию сохранять пробелы у себя.

2023-12-15 06:05 UTC, miks1965 commented
Нужно табы переконвертировать в пробелы

2023-12-17 10:43 UTC, SunSerega commented on Compiler/Compiler.cs
> +            StandardModule module_to_delete = StandardModules.Find(module => module.Name == name);
Можно использовать `.FindIndex` или `.RemoveAll` чтобы хотя бы проходить список только 1 раз, удаляя по условию.

2023-12-17 16:02 UTC, miks1965 commented
Поддерживаю. .FindIndex и потом RemoveAt если нашли

2023-12-17 16:27 UTC, AlexanderZemlyak commented on Compiler/Compiler.cs
> +            StandardModule module_to_delete = StandardModules.Find(module => module.Name == name);
Согласен, недосмотрел.

2023-12-17 16:35 UTC, SunSerega commented on CodeCompletion/SymTable.cs
> +            this.si.description = CodeCompletionController.CurrentParser?.LanguageInformation?.GetDescription(this);
А `LanguageInformation` тоже может быть `null`?

2023-12-17 16:36 UTC, AlexanderZemlyak commented on CodeCompletion/SymTable.cs
> +            this.si.description = CodeCompletionController.CurrentParser?.LanguageInformation?.GetDescription(this);
Ну это если parser null, то и languageInformation будет null, разве нет?

2023-12-17 16:43 UTC, SunSerega commented on CodeCompletion/SymTable.cs
> +            this.si.description = CodeCompletionController.CurrentParser?.LanguageInformation?.GetDescription(this);
Мне тоже изначально казалось что так будет работать, но если подумать - это было бы очень глупо со стороны реализации оператора `?.`
Вместо этого, если слева от `?.` оказывается `null` - все слова через точку справа не обрабатывает. В паскале так же - но потестить так быстрее:
```
##
var a := new class(x := 5);
Println( a?.x.ToString );
a := nil;
Println( a?.x.ToString );
```

2023-12-17 16:46 UTC, AlexanderZemlyak commented on CodeCompletion/SymTable.cs
> +            this.si.description = CodeCompletionController.CurrentParser?.LanguageInformation?.GetDescription(this);
Ааа, действительно.

2023-12-18 19:33 UTC, merged